### PR TITLE
Fixing charmap error seen for text classification on CAirline

### PR DESCRIPTION
**Pull request by yogeshhk**
## Checklist
Please feel free to remove inapplicable items for your PR.
- [ ] The PR title starts with [$CATEGORY] (such as [Doc], [Feature]])
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [ ] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [ ] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../README.md).

### CODE REVIEW

**Comment by AlanSwift** [comment]
The default encoding should be "utf-8".
If users need additional encoding, they should override this function.

**Comment by AlanSwift** [comment]
We will check the encoding problem in text classification on CAirline dataset.
Thank you!

**Comment by AlanSwift** [comment]
Thank you for your interest in our library and reporting the issue! We reproduced the reported error on Windows. A quick fix we found was to change the line to `open(file_path, 'r', encoding=“utf-8”, errors='ignore’)`. We have tested it on Windows/Linux/Mac. May I ask why you chose cp437 encoding over utf-8 encoding considering that utf-8 is more commonly used?

**Comment by yogeshhk** [comment]
As per https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character  one of the comments said that cp437 has ALL the characters...so tried and worked!!

**Comment by yogeshhk** [comment]
@AlanSwift with either of "utf-8" or "cp437", that you find more correct, you can go ahead with merging the pull-request, right?

**Comment by AlanSwift** [comment]
Sorry for the late reply.
After discussing, we think "utf-8" is better.
Could you please change this line to ``open(file_path, 'r', encoding="utf-8")`` and merge it to ``develop`` (not master) branch?
Thank you!

**Comment by AlanSwift** [comment]
Approved!
Thank you!

**Pull request merged**
