### PR TITLE
[Feature] Added Twitter Sentiment dataset for Text Classification, issue #323

### PR DESCRIPTION
**Pull request by yogeshhk**
## Description
Additional Twitter Sentiment analysis dataset 

## Checklist
Please feel free to remove inapplicable items for your PR.
- [x] The PR title starts with [$CATEGORY] (such as [Doc], [Feature]])
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented
- [x] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [x] Related issue is referred in this PR
- [ ] If the PR is for a new model/paper, I've updated the example index [here](../README.md).

### CODE REVIEW

**Comment by AlanSwift** [comment]
Thanks for your contribution.
Could you please report the performance?

**Comment by yogeshhk** [comment]
I have tested with glove 6B model with just 5 epochs to see it works...Sharing performance numbers of that, would it be fine? My hardware wont permit larger glove and more epochs.

**Comment by AlanSwift** [comment]
OK. We will test it for you in few days (less than a week).
I notice that one of the commits is "Added smaller train file to fit 50mb limit issue #323". What does it mean? Are the added twitter training files subsets of original ones?

**Comment by yogeshhk** [comment]
Yes @AlanSwift . There was limit of 50mb on size of file one can upload on github. So, reduced some training samples to get data size down.

**Comment by yogeshhk** [comment]
As this dataset is not getting accepted, can you please delete the pull request? @AlanSwift

**Pull request closed without merging**
