### PR TITLE
[Feature] More efficient BERT (WIP)

### PR DESCRIPTION
**Pull request by j-rossi-nl**
## Description

Relates to #426 

This PR adds a class "FastBertEmbeddings":
* creates a document embeddings by averaging the CLS token embedding of each chunk of text
* allows for batching the chunks (to avoid OOM with CUDA)
* processes a graph where "input_ids" and "input_mask" have been setup (text is tokenized by any of Huggingface tokenizer)
* processes a graph where only "token" is available (then it is much much longer)
* accepts any huggingface transformers model

It is fast:
* it uses preprocessed data
* it uses the embedding of CLS token

It is memory efficient:
* chunks are processed in batches

BertEmbeddings has also been updated, as the map matrix has been made sparse. Nonetheless, it still uses very large amounts of RAM, and can't scale up to texts in the range of 60k words).

**Work in Progress** TEST is still missing.

## Checklist
Please feel free to remove inapplicable items for your PR.
- [*] The PR title starts with [$CATEGORY] (such as [Doc], [Feature]])
- [*] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [*] Code is well-documented
- [ ] To the my best knowledge, examples are either not affected by this change,
      or have been fixed to be compatible with this change
- [*] Related issue is referred in this PR

### CODE REVIEW

**Comment by hugochan** [comment]
@j-rossi-nl Thank you so much for contributing to the library! We will evaluate the PR and get back to you soon.

**Comment by j-rossi-nl** [comment]
Hi, 
I have made this branch specifically tailored to one of my current project, so I would expect it to be far from finished to be included in the library.
If this is of interest to you, I'll go on:
* proper documentation
* tests

**Comment by hugochan** [comment]
> Hi, I have made this branch specifically tailored to one of my current project, so I would expect it to be far from finished to be included in the library. If this is of interest to you, I'll go on:
> 
> * proper documentation
> * tests

@j-rossi-nl thanks for the update! Yes, it would be great if you can go on with documentation and tests so that we can have a better understanding of your implementation. We will then discuss what's the best way to include your contribution to the library.

**Comment by j-rossi-nl** [comment]
Hi,
I missed the notification (EBKAC), but yes I will have a look at that.
First I need to synchronize, I'm now way behind main/HEAD.
Let's say somewhere within the next month.
Regards

**Comment by hugochan** [comment]
> Hi,
> I missed the notification (EBKAC), but yes I will have a look at that.
> First I need to synchronize, I'm now way behind main/HEAD.
> Let's say somewhere within the next month.
> Regards

Hi @j-rossi-nl , thanks again for making this proposal! Can I check what is the current status of this PR? Because this PR has been there for quite a while, we might need to close it if there is no more update in the next couple of weeks.

**Comment by hugochan** [comment]
Closed the PR due to long period of inactivity. Please feel free to reopen it if there is any new update.

**Pull request closed without merging**
